language: node_js
node_js:
  - node
services:
  - postgresql
before_install:
  - npm i jest

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres 
  - psql travis_ci_test < data.sql